aliases: []
creation_timestamp: 1750342581967
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1750342581967
metrics: null
model_id: m-a444a1d109ed4220a563327f605348ec
name: BreastCancerRFModel
params: null
run_id: c0bbee5f842a4ea4b6901dcd3934e0d6
run_link: null
source: models:/m-a444a1d109ed4220a563327f605348ec
status: READY
status_message: null
storage_location: file:///C:/Users/acer/Downloads/JagoanIT/artifacts/977635129933871101/models/m-a444a1d109ed4220a563327f605348ec/artifacts
user_id: null
version: 3
