artifact_uri: file:///C:/Users/acer/Downloads/JagoanIT/artifacts/977635129933871101/c0bbee5f842a4ea4b6901dcd3934e0d6/artifacts
end_time: 1750342582012
entry_point_name: ''
experiment_id: '977635129933871101'
lifecycle_stage: active
run_id: c0bbee5f842a4ea4b6901dcd3934e0d6
run_name: unique-zebra-620
source_name: ''
source_type: 4
source_version: ''
start_time: 1750342574595
status: 3
tags: []
user_id: acer
