aliases: []
creation_timestamp: 1750342611482
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1750342611482
metrics: null
model_id: m-e2740dac30c149ada53e32299e53bb13
name: BreastCancerRFModel
params: null
run_id: 52e318c27f684ac3bc12586637f30719
run_link: null
source: models:/m-e2740dac30c149ada53e32299e53bb13
status: READY
status_message: null
storage_location: file:///C:/Users/acer/Downloads/JagoanIT/artifacts/977635129933871101/models/m-e2740dac30c149ada53e32299e53bb13/artifacts
user_id: null
version: 4
